//------------------------------------------------------------------------------
// <auto-generated>
//------------------------------------------------------------------------------
namespace Training.Admin {
    public partial class TrainingRequirements {
        protected global::System.Web.UI.WebControls.Label lblTraining;
        protected global::System.Web.UI.WebControls.Label lblFeedbackStatus;
        protected global::System.Web.UI.WebControls.TextBox txtFeedbackReason;
        protected global::System.Web.UI.WebControls.Button btnFeedback;
        protected global::System.Web.UI.WebControls.Label lblCertificateStatus;
        protected global::System.Web.UI.WebControls.TextBox txtCertificateReason;
        protected global::System.Web.UI.WebControls.Button btnCertificate;
        protected global::System.Web.UI.WebControls.GridView gvSessions;
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}