CREATE TABLE dbo.ManagerMaster (
    ID INT IDENTITY(1,1) NOT NULL,
    EmpID NVARCHAR(150) NOT NULL,
    MapForLocation NVARCHAR(150) NULL,
    TrainingLocationID NVARCHAR(100) NOT NULL,
    CreatedOn DATETIME NOT NULL CONSTRAINT DF_ManagerMaster_CreatedOn DEFAULT (GETDATE()),
    CreatedBy NVARCHAR(20) NULL,
    ActiveStatus NVARCHAR(20) NULL,
    CONSTRAINT PK_ManagerMaster PRIMARY KEY CLUSTERED (ID)
);