//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training.Admin {
    public partial class ManageTraining {
        protected global::Training.Admin.TrainingSummary TrainingSummary1;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.Button btnUpdateTraining;
        protected global::System.Web.UI.WebControls.Button btnAssignSession;
        protected global::System.Web.UI.WebControls.Button btnAssignTrainee;
        protected global::System.Web.UI.WebControls.Button btnCertificateTemplate;
        protected global::System.Web.UI.WebControls.Button btnAssignHostel;
        protected global::System.Web.UI.WebControls.Button btnStartTraining;
        protected global::System.Web.UI.WebControls.Button btnAttendance;
        protected global::System.Web.UI.WebControls.Panel pnlHostelConfirmation;
        protected global::System.Web.UI.WebControls.Button btnHostelYes;
        protected global::System.Web.UI.WebControls.Button btnHostelNo;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Literal litBatchLifecycle;
    }
}
